---
language: python

sudo: required

services:
  - docker

install:
  - pip install pipenv
  - pipenv install --ignore-pipfile

script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
