---
- name: Ensure the necessary packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - postfix
    - libsasl2-modules

- name: Ensure the postfix config file is set
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "{{ item.match }}"
    line: "{{ item.line }}"
  notify: restart postfix
  with_items:
    - { match: '^compatibility_level =',        line: "compatibility_level = {{ secure_emailer_compatibility_level }}" }
    - { match: '^myhostname =',                 line: "myhostname = {{ secure_emailer_fqdn }}" }
    - { match: '^inet_protocols =',             line: "inet_protocols = {{ secure_emailer_inet_protocols }}" }
    - { match: '^relayhost =',                  line: "relayhost = [{{ secure_emailer_relay_server_name }}]:{{ secure_emailer_relay_server_port }}" }
    - { match: '^smtp_address_preference =',    line: "smtp_address_preference = {{ secure_emailer_smtp_address_preference }}" }
    - { match: '^smtp_sasl_auth_enable =',      line: "smtp_sasl_auth_enable = yes" }
    - { match: '^smtp_sasl_security_options =', line: "smtp_sasl_security_options = noanonymous" }
    - { match: '^smtp_sasl_password_maps =',    line: "smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd" }
    - { match: '^smtp_tls_security_level =',    line: "smtp_tls_security_level = encrypt" }
    - { match: '^smtp_tls_CAfile =',            line: "smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt" }

- name: Ensure the SASL password is set for the relay mail service
  lineinfile:
    path: /etc/postfix/sasl/sasl_passwd
    regexp: '^\[{{ secure_emailer_relay_server_name }}\]:'
    line: "[{{ secure_emailer_relay_server_name }}]:{{ secure_emailer_relay_server_port }} \
          {{ secure_emailer_relay_server_username }}:{{ secure_emailer_relay_server_password }}"
    create: true
    mode: 0600
  no_log: true
  notify:
    - regenerate postfix database hash
    - restart postfix
