---
- name: Ensure the necessary packages are installed
  package: name="{{ item }}" state=present
  with_items:
      - postfix
      - libsasl2-modules

- name: Ensure the protocol is limited to ipv4
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^inet_protocols ='
    line: "inet_protocols = all"
  notify: restart postfix

# Maybe the "all" option works for everyone?
# - name: Ensure the protocol is limited to ipv4
#   lineinfile:
#     path: /etc/postfix/main.cf
#     regexp: '^inet_protocols ='
#     line: "inet_protocols = ipv4, ipv6"
#   notify: restart postfix
#   when: secure_emailer_allow_ipv6
#
# - name: Ensure the protocol is limited to ipv4
#   lineinfile:
#     path: /etc/postfix/main.cf
#     regexp: '^inet_protocols ='
#     line: "inet_protocols = ipv4"
#   notify: restart postfix
#   when: not secure_emailer_allow_ipv6


- name: Ensure the domain name is set
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^myhostname ='
    line: "myhostname = {{ secure_emailer_fqdn }}"
  notify: restart postfix

- name: Ensure the SASL password is set for the relay mail service
  lineinfile:
    path: /etc/postfix/sasl/sasl_passwd
    regexp: '^\[{{ secure_emailer_relay_server_name }}\]:'
    line: "[{{ secure_emailer_relay_server_name }}]:{{ secure_emailer_relay_server_port }} {{ secure_emailer_relay_server_username }}:{{ secure_emailer_relay_server_password }}"
    create: yes
  register: _sasl_passwords_changed
  notify: restart postfix

- name: Regenerate the hash db, if the passwords changed
  command: postmap /etc/postfix/sasl/sasl_passwd
  notify: restart postfix
  when: _sasl_passwords_changed.changed

- name: Ensure the sasl password file and db are properly secured
  file: path="{{ item }}" mode=0600 owner=root group=root
  with_items:
      - /etc/postfix/sasl/sasl_passwd
      - /etc/postfix/sasl/sasl_passwd.db

- name: Ensure the postfix config file is set
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "{{ item.match }}"
    line: "{{ item.line }}"
  notify: restart postfix
  with_items:
      - { match: '^relayhost =', line: "relayhost = [{{ secure_emailer_relay_server_name }}]:{{ secure_emailer_relay_server_port }}" }
      - { match: '^smtp_sasl_auth_enable =', line: "smtp_sasl_auth_enable = yes" }
      - { match: '^smtp_sasl_security_options =', line: "smtp_sasl_security_options = noanonymous" }
      - { match: '^smtp_sasl_password_maps =', line: "smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd" }
      - { match: '^smtp_tls_security_level =', line: "smtp_tls_security_level = encrypt" }
      - { match: '^smtp_tls_CAfile =', line: "smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt" }
