---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1804}-ansible:latest"
    tty: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    override_command: false
    environment:
      container: docker
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ANSIBLE0016
  inventory:
    group_vars:
      all:
        secure_emailer_fqdn: testsite.local
        secure_emailer_relay_server_name: smtp.gmail.com
        secure_emailer_relay_server_port: 587
        secure_emailer_relay_server_username: testuser
        secure_emailer_relay_server_password: testpassword

verifier:
  name: testinfra
  lint:
    name: flake8
