---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: xenial
    image: triplepoint/ubuntu-systemd-16.04
    privileged: true
    command: /bin/bash -c "exec /sbin/init --log-target=journal 3>&1"
#   - name: bionic
#     image: triplepoint/ubuntu-systemd-18.04
#     privileged: true
#     command: /bin/bash -c "exec /sbin/init --log-target=journal 3>&1"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ANSIBLE0016
  inventory:
    group_vars:
      all:
        secure_emailer_fqdn: testsite.local
        secure_emailer_relay_server_name: smtp.gmail.com
        secure_emailer_relay_server_port: 587
        secure_emailer_relay_server_username: testuser
        secure_emailer_relay_server_password: testpassword

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
